"use server";

import { v4 as uuidv4 } from 'uuid';

const BACKEND_URL = process.env.NEXT_PUBLIC_BACKEND_URL;

if (!BACKEND_URL) {
  throw new Error("Missing NEXT_PUBLIC_BACKEND_URL environment variable");
}

export async function createSession(): Promise<string> {
  const response = await fetch(`${BACKEND_URL}/create_session`, {
    method: 'POST',
  });
  if (!response.ok) {
    throw new Error('Failed to create session');
  }
  const data = await response.json();
  console.log(`Session created: ${data.session_id}`);
  return data.session_id;
}


export async function buildIndex(sessionId: string): Promise<{ success: boolean }> {
  console.log(`Building index for session: ${sessionId}`);
  const formData = new FormData();
  formData.append('session_id', sessionId);

  const response = await fetch(`${BACKEND_URL}/build_index`, {
    method: 'POST',
    body: formData,
  });

  if (!response.ok) {
    const error = await response.json();
    console.error(`Index build failed for session ${sessionId}:`, error);
    throw new Error(error.detail || 'Index building failed');
  }

  const result = await response.json();
  console.log(`Index built successfully for session: ${sessionId}`, result);
  return { success: true };
}


export async function getCombinedResourceText(sessionId: string): Promise<string> {
  // This function might not be needed anymore if notes are generated by the backend directly
  // For now, it's not connected to a backend endpoint.
  return `The mitochondria is the powerhouse of the cell.`;
}

export async function evaluateAnswer(sessionId: string, questionNum: number, userAnswer: string): Promise<{ score: number, feedback: string, correct_answer: string }> {
  const formData = new FormData();
  formData.append('session_id', sessionId);
  formData.append('question_num', String(questionNum));
  formData.append('user_answer', userAnswer);

  const response = await fetch(`${BACKEND_URL}/submit_answer`, {
    method: 'POST',
    body: formData,
  });

  if (!response.ok) {
    const error = await response.json();
    throw new Error(error.detail || "Failed to evaluate answer.");
  }
  
  const data = await response.json();

  // The backend returns score 0, 0.5, or 1. We convert to percentage.
  // It also returns `missing_keypoints` which we can use in feedback.
  return {
    score: data.score * 100,
    feedback: data.feedback,
    correct_answer: data.correct_answer || 'N/A'
  };
}

export async function finishQuiz(sessionId: string): Promise<{ accuracy: number; strong_topics: string[]; weak_topics: string[]; topic_strength: Record<string, number> }> {
  const formData = new FormData();
  formData.append('session_id', sessionId);
  
  const response = await fetch(`${BACKEND_URL}/finish_quiz`, {
      method: 'POST',
      body: formData,
  });

  if(!response.ok) {
    const error = await response.json();
    throw new Error(error.detail || "Failed to finalize quiz results.");
  }

  const summary = await response.json();
  
  return {
    accuracy: parseFloat(summary.overall_accuracy.toFixed(1)),
    strong_topics: summary.strong_topics,
    weak_topics: summary.weak_topics,
    topic_strength: summary.topic_strength
  };
}

export async function resetSession(sessionId: string): Promise<{ success: boolean }> {
  const formData = new FormData();
  formData.append('session_id', sessionId);
  const response = await fetch(`${BACKEND_URL}/reset`, {
    method: 'POST',
    body: formData,
  });

  if (!response.ok) {
    return { success: false };
  }
  return { success: true };
}
